In [1]:
import pandas as pd

df = pd.read_csv("StudentsPerformance.csv")

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

display(df.head())

Dataset loaded successfully!
Dataset shape: (1000, 8)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [2]:
print("Missing values in each column:")
print(df.isnull().sum())

print("\nTotal missing values:", df.isnull().sum().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nColumn data types:")
print(df.dtypes)

Missing values in each column:
gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

Total missing values: 0

Duplicate rows: 0

Column data types:
gender                           str
race/ethnicity                   str
parental level of education      str
lunch                            str
test preparation course          str
math score                     int64
reading score                  int64
writing score                  int64
dtype: object

In [3]:
# Keep a copy of the original data
cleaned_df = df.copy()

# Remove duplicate rows
cleaned_df = cleaned_df.drop_duplicates()

# Fill missing numerical values with their median
numeric_cols = cleaned_df.select_dtypes(
    include="number"
).columns

for col in numeric_cols:
    cleaned_df[col] = cleaned_df[col].fillna(
        cleaned_df[col].median()
    )

# Fill missing text values with the mode
text_cols = cleaned_df.select_dtypes(
    include=["object", "string"]
).columns

for col in text_cols:
    if cleaned_df[col].isnull().any():
        mode_values = cleaned_df[col].mode()
        if not mode_values.empty:
            cleaned_df[col] = cleaned_df[col].fillna(
                mode_values.iloc[0]
            )

# Remove unnecessary spaces from text columns
for col in text_cols:
    cleaned_df[col] = cleaned_df[col].apply(
        lambda x: x.strip() if isinstance(x, str) else x
    )

print("Original rows:", len(df))
print("Cleaned rows:", len(cleaned_df))
print("Missing values after cleaning:")
print(cleaned_df.isnull().sum())

Original rows: 1000
Cleaned rows: 1000
Missing values after cleaning:
gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [4]:
cleaned_df.to_csv("cleaned_students_performance.csv",
                  index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [5]:
print("Final dataset shape:", cleaned_df.shape)
print("Remaining duplicates:", cleaned_df.duplicated().sum())
display(cleaned_df.head())

Final dataset shape: (1000, 8)
Remaining duplicates: 0

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# SWYNEX – Data Cleaning & Preparation

## Project Overview
This project focuses on cleaning and preparing a public Students Performance in Exams dataset for analysis using Python and Pandas.

## Tasks Performed
- Inspected the dataset and its column data types.
- Checked for missing values and duplicate records.
- Removed duplicate rows where present.
- Handled missing numerical and categorical values where necessary.
- Standardized whitespace in text columns.
- Verified the cleaned dataset and exported it as a CSV file.

## Tools Used
- Python
- Pandas
- Jupyter Notebook

## Files Included
- `data_cleaning.ipynb` – Data cleaning code and verification.
- `cleaned_students_performance.csv` – Cleaned dataset.

## Result
The dataset was inspected, cleaned where necessary, and exported for further analysis. Actual changes and final row counts are documented in the notebook output.